DROP TABLE Proposals CASCADE;
DROP TABLE Funds CASCADE;
DROP TABLE Members CASCADE;
DROP TABLE Expenses CASCADE;
DROP TABLE Committee CASCADE;
DROP TABLE FrontPageNews CASCADE;
Drop TABLE InfoText CASCADE;

